<footer>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <p><img src="images/DMFooter.png" width = "200px"></p>
          <p><b>© Dans La Mort 2016</b><br>
                Designed by Jonah Barlow<br>
                Contact information: <a href="mailto:jonahb@email.uscupstate.edu">
                jonahb@email.uscupstate.edu</a>.</p></div>
      </div>
    </div>
  </footer>
</html>