INSERT INTO Category(category,gender) VALUES('shirt','M');
INSERT INTO Category(category,gender) VALUES('dress','F');
INSERT INTO Category(category,gender) VALUES('top','F');
INSERT INTO Category(category,gender) VALUES('shoe','M');
INSERT INTO Category(category,gender) VALUES('shoe','F');
INSERT INTO Category(category,gender) VALUES('skirt','F');
INSERT INTO Category(category,gender) VALUES('pant','M');
INSERT INTO Category(category,gender) VALUES('sweater','F');
INSERT INTO Category(category,gender) VALUES('sweater','M');
INSERT INTO Category(category,gender) VALUES('jacket','M');
INSERT INTO Category(category,gender) VALUES('jacket','F');

INSERT INTO Brands(name,brand) VALUES('Armani','armani');
INSERT INTO Brands(name,brand) VALUES('BCBG','bcbg');
INSERT INTO Brands(name,brand) VALUES('Hugo Boss','hugoboss');
INSERT INTO Brands(name,brand) VALUES('Lanvin','lanvin');
INSERT INTO Brands(name,brand) VALUES('Louboutin','louboutin');
INSERT INTO Brands(name,brand) VALUES('Marc Jacobs','marcjacobs');
INSERT INTO Brands(name,brand) VALUES('Versace','versace');
INSERT INTO Brands(name,brand) VALUES('Vince Camuto','vincecamuto');
INSERT INTO Brands(name,brand) VALUES('Yohji Yamamoto','yohjiyamamoto');

INSERT INTO Sizes(sizes,category,gender) VALUES('Small','top','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('Small','jacket','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('Small','jacket','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('Small','sweater','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('Small','sweater','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('Medium','top','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('Medium','jacket','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('Medium','jacket','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('Medium','sweater','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('Medium','sweater','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('Large','top','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('Large','jacket','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('Large','jacket','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('Large','sweater','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('Large','sweater','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('XL','top','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('XL','jacket','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('XL','jacket','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('XL','sweater','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('XL','sweater','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('XXL','top','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('XXL','jacket','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('XXL','jacket','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('XXL','sweater','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('XXL','sweater','M');

INSERT INTO Sizes(sizes,category,gender) VALUES('0','dress','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('2','dress','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('4','dress','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('6','dress','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('8','dress','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('10','dress','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('12','dress','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('0','skirt','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('2','skirt','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('4','skirt','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('6','skirt','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('8','skirt','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('10','skirt','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('12','skirt','F');

INSERT INTO Sizes(sizes,category,gender) VALUES('6 1/2','shoe','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('7','shoe','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('7 1/2','shoe','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('8','shoe','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('8 1/2','shoe','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('9','shoe','F');
INSERT INTO Sizes(sizes,category,gender) VALUES('7','shoe','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('7 1/2','shoe','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('8','shoe','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('8 1/2','shoe','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('9','shoe','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('9 1/2','shoe','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('10','shoe','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('10 1/2','shoe','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('11','shoe','M');

INSERT INTO Sizes(sizes,category,gender) VALUES('15 1/2 32/33','shirt','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('15 1/2 34/35','shirt','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('16 32/33','shirt','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('16 34/35','shirt','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('16 1/2 32/33','shirt','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('16 1/2 34/35','shirt','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('17 32/33','shirt','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('17 34/35','shirt','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('17 1/2 32/33','shirt','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('17 1/2 34/35','shirt','M');

INSERT INTO Sizes(sizes,category,gender) VALUES('30x30','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('30x32','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('30x34','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('30x36','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('32x30','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('32x32','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('32x34','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('32x36','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('34x30','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('34x32','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('34x34','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('34x36','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('36x30','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('36x32','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('36x34','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('36x36','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('38x32','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('38x34','pant','M');
INSERT INTO Sizes(sizes,category,gender) VALUES('38x36','pant','M');


INSERT INTO States(abbr) VALUES('AL');
INSERT INTO States(abbr) VALUES('AK');
INSERT INTO States(abbr) VALUES('AZ');
INSERT INTO States(abbr) VALUES('AR');
INSERT INTO States(abbr) VALUES('CA');
INSERT INTO States(abbr) VALUES('CO');
INSERT INTO States(abbr) VALUES('CT');
INSERT INTO States(abbr) VALUES('DE');
INSERT INTO States(abbr) VALUES('FL');
INSERT INTO States(abbr) VALUES('GA');
INSERT INTO States(abbr) VALUES('HI');
INSERT INTO States(abbr) VALUES('ID');
INSERT INTO States(abbr) VALUES('IL');
INSERT INTO States(abbr) VALUES('IN');
INSERT INTO States(abbr) VALUES('IA');
INSERT INTO States(abbr) VALUES('KS');
INSERT INTO States(abbr) VALUES('KY');
INSERT INTO States(abbr) VALUES('LA');
INSERT INTO States(abbr) VALUES('ME');
INSERT INTO States(abbr) VALUES('MD');
INSERT INTO States(abbr) VALUES('MA');
INSERT INTO States(abbr) VALUES('MI');
INSERT INTO States(abbr) VALUES('MN');
INSERT INTO States(abbr) VALUES('MS');
INSERT INTO States(abbr) VALUES('MO');
INSERT INTO States(abbr) VALUES('MT');
INSERT INTO States(abbr) VALUES('NE');
INSERT INTO States(abbr) VALUES('NV');
INSERT INTO States(abbr) VALUES('NH');
INSERT INTO States(abbr) VALUES('NJ');
INSERT INTO States(abbr) VALUES('NM');
INSERT INTO States(abbr) VALUES('NY');
INSERT INTO States(abbr) VALUES('NC');
INSERT INTO States(abbr) VALUES('ND');
INSERT INTO States(abbr) VALUES('OH');
INSERT INTO States(abbr) VALUES('OK');
INSERT INTO States(abbr) VALUES('OR');
INSERT INTO States(abbr) VALUES('PA');
INSERT INTO States(abbr) VALUES('RI');
INSERT INTO States(abbr) VALUES('SC');
INSERT INTO States(abbr) VALUES('SD');
INSERT INTO States(abbr) VALUES('TN');
INSERT INTO States(abbr) VALUES('TX');
INSERT INTO States(abbr) VALUES('UT');
INSERT INTO States(abbr) VALUES('VT');
INSERT INTO States(abbr) VALUES('VA');
INSERT INTO States(abbr) VALUES('WA');
INSERT INTO States(abbr) VALUES('WV');
INSERT INTO States(abbr) VALUES('WI');
INSERT INTO States(abbr) VALUES('WY');